queue_rules:
    - name: default
      batch_size: 8
      batch_max_wait_time: 60 s
      checks_timeout: 10800 s
      merge_method: squash
      commit_message_template: |
          {{ title }} (#{{ number }})

          {% for commit in commits %}
          * {{ commit.commit_message }}
          {% endfor %}

pull_request_rules:
    - name: default
      conditions:
          - base=unstable
      actions:
          rebase:
