queue_rules:
    - name: stable
      batch_size: 8
      batch_max_wait_time: 60 s
      checks_timeout: 10800 s
      merge_method: merge
      commit_message_template: |
          {{ title }} (#{{ number }})

          {% for commit in commits %}
          * {{ commit.commit_message }}
          {% endfor %}

    - name: unstable
      batch_size: 8
      batch_max_wait_time: 60 s
      checks_timeout: 10800 s
      merge_method: squash
      commit_message_template: |
          {{ title }} (#{{ number }})

          {% for commit in commits %}
          * {{ commit.commit_message }}
          {% endfor %}

    - name: feature
      batch_size: 8
      batch_max_wait_time: 60 s
      checks_timeout: 10800 s
      merge_method: squash
      commit_message_template: |
          {{ title }} (#{{ number }})

          {% for commit in commits %}
          * {{ commit.commit_message }}
          {% endfor %}
