[workspace]
members = [
    "tokenscout",

    "database",


    "common/logger",
    "common/metrics",

    "analyzer",
    "analyzer/security",

    "telegram-bot",

    "ranker",
]
resolver = "2"

[workspace.package]
edition = "2021"

[workspace.dependencies]
