coverage:
    status:
        patch: off
        project:
            default:
                threshold: null
                informational: true
github_checks:
    annotations: false
comment:
    layout: "reach, files, flags, components"
    require_changes: true
