use std::collections::HashMap;

pub struct RpcList {
    pub endpoints: HashMap<String, Vec<String>>,
}

impl RpcList {
    pub fn new() -> Self {
        let mut endpoints = HashMap::new();
        endpoints.insert(
            "ethereum".to_string(),
            vec![
                "https://eth.llamarpc.com".to_string(),
                "https://rpc.builder0x69.io".to_string(),
                "https://eth-pokt.nodies.app".to_string(),
                "https://rpc.public.curie.radiumblock.co/http/ethereum".to_string(),
                "https://eth-mainnet.public.blastapi.io".to_string(),
                "https://eth-mainnet.rpcfast.com?api_key=xbhWBI1Wkguk8SNMu1bvvLurPGLXmgwYeC4S6g2H7WdwFigZSmPWVZRxrskEQwIf".to_string(),
                "https://rpc.ankr.com/eth".to_string(),
                "https://ethereum.blockpi.network/v1/rpc/public".to_string(),
                "https://eth.drpc.org".to_string(),
                "https://core.gashawk.io/rpc".to_string(),
                "https://rpc.mevblocker.io/noreverts".to_string(),
                "https://rpc.mevblocker.io".to_string(),
                "https://ethereum-rpc.publicnode.com".to_string(),
                "https://virginia.rpc.blxrbdn.com".to_string(),
                "https://ethereum.rpc.subquery.network/public".to_string(),
                "https://mainnet.gateway.tenderly.co".to_string(),
                "https://gateway.tenderly.co/public/mainnet".to_string(),
                "wss://ethereum-rpc.publicnode.com".to_string(),
                "wss://eth.drpc.org".to_string(),
                "https://eth.rpc.blxrbdn.com".to_string(),
                "https://uk.rpc.blxrbdn.com".to_string(),
                "https://rpc.payload.de".to_string(),
                "https://rpc.mevblocker.io/fullprivacy".to_string(),
                "https://endpoints.omniatech.io/v1/eth/mainnet/public".to_string(),
                "https://rpc.mevblocker.io/fast".to_string(),
                "https://eth.api.onfinality.io/public".to_string(),
                "https://public.stackup.sh/api/v1/node/ethereum-mainnet".to_string(),
                "https://1rpc.io/eth".to_string(),
                "https://rpc.graffiti.farm".to_string(),
                "https://rpc.eth.gateway.fm".to_string(),
                "https://eth.meowrpc.com".to_string(),
                "https://singapore.rpc.blxrbdn.com".to_string(),
                "wss://mainnet.gateway.tenderly.co".to_string(),
                "https://api.tatum.io/v3/blockchain/node/ethereum-mainnet".to_string(),
                "https://api.zan.top/node/v1/eth/mainnet/public".to_string(),
                "https://api.securerpc.com/v1".to_string(),
                "https://rpc.lokibuilder.xyz/wallet".to_string(),
                "wss://eth-mainnet.4everland.org/ws/v1/37fa9972c1b1cd5fab542c7bdd4cde2f".to_string(),
                "https://eth.nodeconnect.org".to_string(),
                "https://rpc.flashbots.net/fast".to_string(),
                "https://api.stateless.solutions/ethereum/v1/demo".to_string(),
                "https://eth.merkle.io".to_string(),
                "https://rpc.flashbots.net".to_string(),
            ],
        );
        endpoints.insert("bsc".to_string(), 
        vec![
                "https://binance.llamarpc.com".to_string(),
                "https://api.zan.top/node/v1/bsc/mainnet/public".to_string(),
                "wss://bsc-rpc.publicnode.com".to_string(),
                "https://bsc-mainnet.rpcfast.com?api_key=xbhWBI1Wkguk8SNMu1bvvLurPGLXmgwYeC4S6g2H7WdwFigZSmPWVZRxrskEQwIf".to_string(),
                "https://bsc-rpc.publicnode.com".to_string(),
                "https://bsc-mainnet.public.blastapi.io".to_string(),
                "https://bsc.drpc.org".to_string(),
                "https://rpc-bsc.48.club".to_string(),
                "https://koge-rpc-bsc.48.club".to_string(),
                "https://bsc.blockpi.network/v1/rpc/public".to_string(),
                "https://endpoints.omniatech.io/v1/bsc/mainnet/public".to_string(),
                "https://public.stackup.sh/api/v1/node/bsc-mainnet".to_string(),
                "https://bsc.meowrpc.com".to_string(),
                "https://api.tatum.io/v3/blockchain/node/bsc-mainnet".to_string(),
                "https://bsc-pokt.nodies.app".to_string(),
                "https://rpc.ankr.com/bsc".to_string(),
                "https://bsc.rpc.blxrbdn.com".to_string(),
                "https://bsc-mainnet.4everland.org/v1/37fa9972c1b1cd5fab542c7bdd4cde".to_string(),
                "https://bnb.rpc.subquery.network/public".to_string(),
                "https://1rpc.io/bnb".to_string(),
                "https://bnb.api.onfinality.io/public".to_string(),
                "https://bsc-dataseed.bnbchain.org".to_string(),
                "https://bsc-dataseed4.ninicoin.io".to_string(),
                "https://bscrpc.com".to_string(),
                "https://bsc-dataseed4.defibit.io".to_string(),
                "https://bsc-dataseed3.ninicoin.io".to_string(),
                "https://bsc-dataseed4.bnbchain.org".to_string(),
                "https://bsc-dataseed1.bnbchain.org".to_string(),
                "https://bsc-dataseed2.bnbchain.org".to_string(),
                "https://binance.nodereal.io".to_string(),
                "https://bsc-dataseed3.bnbchain.org".to_string(),
                "https://bsc-dataseed1.ninicoin.io".to_string(),
                "https://bsc-dataseed1.defibit.io".to_string(),
                "https://bsc-dataseed2.defibit.io".to_string(),
                "https://bsc-dataseed2.ninicoin.io".to_string(),
                "https://bsc-dataseed3.defibit.io".to_string(),
                "https://bsc-mainnet.nodereal.io/v1/64a9df0874fb4a93b9d0a3849de012d3".to_string(),
        ]);
        endpoints.insert(
            "polygon".to_string(),
            vec![
                "https://polygon.llamarpc.com".to_string(),
                "wss://polygon.drpc.org".to_string(),
                "wss://polygon-bor-rpc.publicnode.com".to_string(),
                "https://public.stackup.sh/api/v1/node/polygon-mainnet".to_string(),
                "https://polygon.blockpi.network/v1/rpc/public".to_string(),
                "https://polygon.meowrpc.com".to_string(),
                "https://api.zan.top/node/v1/polygon/mainnet/public".to_string(),
                "https://polygon-bor-rpc.publicnode.com".to_string(),
                "https://polygon.drpc.org".to_string(),
                "https://polygon-pokt.nodies.app".to_string(),
                "https://polygon-mainnet.public.blastapi.io".to_string(),
                "https://polygon.rpc.blxrbdn.com".to_string(),
                "https://api.tatum.io/v3/blockchain/node/polygon-mainnet".to_string(),
                "https://polygon-mainnet.4everland.org/v1/37fa9972c1b1cd5fab542c7bdd4cde2f"
                    .to_string(),
                "https://polygon.api.onfinality.io/public".to_string(),
                "https://rpc-mainnet.matic.quiknode.pro".to_string(),
                "https://1rpc.io/matic".to_string(),
                "https://endpoints.omniatech.io/v1/matic/mainnet/public".to_string(),
                "https://polygon.gateway.tenderly.co".to_string(),
                "https://polygon.rpc.subquery.network/public".to_string(),
                "https://gateway.tenderly.co/public/polygon".to_string(),
                "https://rpc.ankr.com/polygon".to_string(),
                "https://polygon-rpc.com".to_string(),
            ],
        );
        endpoints.insert(
            "arbitrum".to_string(),
            vec![
                "https://arbitrum.llamarpc.com".to_string(),
                "https://1rpc.io/arb".to_string(),
                "wss://arbitrum-one-rpc.publicnode.com".to_string(),
                "wss://arbitrum-one.publicnode.com".to_string(),
                "https://arb-pokt.nodies.app".to_string(),
                "https://arbitrum.blockpi.network/v1/rpc/public".to_string(),
                "https://arbitrum.drpc.org".to_string(),
                "https://rpc.ankr.com/arbitrum".to_string(),
                "https://public.stackup.sh/api/v1/node/arbitrum-one".to_string(),
                "https://arbitrum-one.public.blastapi.io".to_string(),
                "https://endpoints.omniatech.io/v1/arbitrum/one/public".to_string(),
                "https://api.zan.top/node/v1/arb/one/public".to_string(),
                "https://arbitrum-one-rpc.publicnode.com".to_string(),
                "https://arbitrum.meowrpc.com".to_string(),
                "https://arb1.arbitrum.io/rpc".to_string(),
                "https://arbitrum.rpc.subquery.network/public".to_string(),
                "https://arbitrum-one.publicnode.com".to_string(),
            ],
        );
        endpoints.insert(
            "base".to_string(),
            vec![
                "https://base.llamarpc.com".to_string(),
                "wss://base-rpc.publicnode.com".to_string(),
                "https://1rpc.io/base".to_string(),
                "https://base.blockpi.network/v1/rpc/public".to_string(),
                "https://base-pokt.nodies.app".to_string(),
                "https://base.gateway.tenderly.co".to_string(),
                "https://base-rpc.publicnode.com".to_string(),
                "https://gateway.tenderly.co/public/base".to_string(),
                "https://api.tatum.io/v3/blockchain/node/base-mainnet".to_string(),
                "wss://base.gateway.tenderly.co".to_string(),
                "https://base.meowrpc.com".to_string(),
                "https://base.drpc.org".to_string(),
                "https://public.stackup.sh/api/v1/node/base-mainnet".to_string(),
                "https://base-mainnet.public.blastapi.io".to_string(),
                "https://base.rpc.subquery.network/public".to_string(),
                "https://endpoints.omniatech.io/v1/base/mainnet/public".to_string(),
                "https://mainnet.base.org".to_string(),
                "https://developer-access-mainnet.base.org".to_string(),
            ],
        );
        endpoints.insert(
            "solana".to_string(),
            vec![
                "https://api.tatum.io/v3/blockchain/node/solana-mainnet".to_string(),
                "https://rpc.ankr.com/solana".to_string(),
            ],
        );

        RpcList { endpoints }
    }

    pub fn add_custom_endpoints(&mut self, chain: &str, urls: Vec<String>) {
        self.endpoints.insert(chain.to_string(), urls);
    }

    pub fn get_endpoints(&self, chain: &str) -> Option<&Vec<String>> {
        self.endpoints.get(chain)
    }
}
